// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0v4iSqBely4YnHIww209HPReIJaP0dkk',
    appId: '1:625279979865:web:2ecbbf8ca588f88925fc48',
    messagingSenderId: '625279979865',
    projectId: 'myshop-26cd2',
    authDomain: 'myshop-26cd2.firebaseapp.com',
    storageBucket: 'myshop-26cd2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYq9Mw6QN0GxDXdg785fqOy73WJ-uS7Q0',
    appId: '1:625279979865:android:37248d990231329125fc48',
    messagingSenderId: '625279979865',
    projectId: 'myshop-26cd2',
    storageBucket: 'myshop-26cd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7nhZMeQ0E85MakHFEPyG6Enjd1Bp8H6k',
    appId: '1:625279979865:ios:6933df000a5734dd25fc48',
    messagingSenderId: '625279979865',
    projectId: 'myshop-26cd2',
    storageBucket: 'myshop-26cd2.appspot.com',
    iosBundleId: 'com.iqboljon.g5.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7nhZMeQ0E85MakHFEPyG6Enjd1Bp8H6k',
    appId: '1:625279979865:ios:c7862ccbe426e3f325fc48',
    messagingSenderId: '625279979865',
    projectId: 'myshop-26cd2',
    storageBucket: 'myshop-26cd2.appspot.com',
    iosBundleId: 'com.iqboljon.g5.shopApp.RunnerTests',
  );
}
